---
# This file contains the default configuration for application logging. Refer to
# the logging documentation[1] for a tutorial and reference for this file.
#
# [1]: https://docs.python.org/3/library/logging.html#module-logging

# The "version" of the schema for the logging config
version: 1
# The root logger writes to the console and includes even the fines log-messages
root:
  level: DEBUG
  handlers: [console]
loggers:
  # The "uvicorn" (embedded web-server) logger propagates all messages
  uvicorn:
    level: DEBUG
  httpx:
    level: WARNING
  # The "httpcore" logger propagates only messages of severity "WARNING" and up
  httpcore:
    level: WARNING
  auth:
    level: DEBUG
  juudge:
    level: DEBUG
  multipart:
    level: WARNING
handlers:
  # Console output uses the "gouge" formatter for colored output, writes to
  # stdout and includes all messages (including DEBUG) if they were not already
  # filtered out by a logger.
  console:
    class: logging.StreamHandler
    formatter: gouge
    level: DEBUG
    stream: ext://sys.stdout
formatters:
  # The "gouge" formatter delegated formatting to the "gouge" library
  gouge:
    class: juudge.web.web.LogFormatter
