---
version: '3.8'
services:
  app:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
    command: sleep infinity
    volumes: [..:/workspace:cached]
  database:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: langchain
      POSTGRES_PASSWORD: langchain
      POSTGRES_DB: langchain
    volumes: [postgres_data:/var/lib/postgresql/data]
volumes:
  postgres_data:
