---
version: '3.8'
services:
  app:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
    command: sleep infinity
    volumes: [..:/workspace:cached]
  database:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: langchain
      POSTGRES_PASSWORD: langchain
      POSTGRES_DB: langchain
    volumes:
      - postgres_data:/var/lib/postgresql/data
#  weaviate:
#    image: cr.weaviate.io/semitechnologies/weaviate:1.27.2
#    command:
#    - --host
#    - 0.0.0.0
#    - --port
#    - '8080'
#    - --scheme
#    - http
#    volumes:
#    - weaviate_data:/var/lib/weaviate
#    restart: on-failure:0
#    environment:
#      QUERY_DEFAULTS_LIMIT: 25
#      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
#      AUTHENTICATION_APIKEY_ALLOWED_KEYS: my-api-key
#      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
#      DEFAULT_VECTORIZER_MODULE: 'none'
#      ENABLE_API_BASED_MODULES: 'true'
#      CLUSTER_HOSTNAME: 'node1'
volumes:
  weaviate_data:
  postgres_data:
